services:
  db:
    image: mongo:latest
    container_name: mongodb
    networks:
      - cashflow
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["mongod", "--auth"]

  backend:
    image: cashflow_backend:latest
    depends_on:
      - db
    networks:
      - cashflow
    environment:
      DB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/admin

  frontend:
    image: cashflow_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - cashflow

networks:
  cashflow:
    external: true
